{
 "title": "Main dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"temperature\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"humidity\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"iaq\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"co2\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"humidity\")"
    }
   ]
  },
  {
   "title": "Indoor Air Quality index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"iaq\")"
    }
   ]
  },
  {
   "title": "Co2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"co2\")"
    }
   ]
  },
  {
   "title": "Volatile Organic Compounds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"voc\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "Mean",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\")\r\n  |> filter(fn: (r) => contains(value: r._field, set: [\"temperature\", \"humidity\", \"pressure\", \"iaq\", \"voc\", \"co2\"]))\r\n"
    }
   ]
  },
  {
   "title": "IAQ Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"logger1\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\" and r._field == \"iaq_acc\")"
    }
   ]
  }
 ]
}